// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'const',
    appId: '1:52071196214:web:b321696227967abcb85a97',
    messagingSenderId: '52071196214',
    projectId: 'lifeos-63a2c',
    authDomain: 'lifeos-63a2c.firebaseapp.com',
    storageBucket: 'lifeos-63a2c.firebasestorage.app',
    measurementId: 'G-EM4LX3Z9ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3V0AgdVPqxlfOZGXepFzda2XAd1piyc',
    appId: '1:52071196214:android:1eab1bc7fb20aa59b85a97',
    messagingSenderId: '52071196214',
    projectId: 'lifeos-63a2c',
    storageBucket: 'lifeos-63a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehaqWATpMdSJLXuUjFOY4dTLKRepu1gQ',
    appId: '1:52071196214:ios:c0aedf0c37e32446b85a97',
    messagingSenderId: '52071196214',
    projectId: 'lifeos-63a2c',
    storageBucket: 'lifeos-63a2c.firebasestorage.app',
    iosClientId: '52071196214-sbc2mqc8cth2b2a1r1pjiili0oo4qhep.apps.googleusercontent.com',
    iosBundleId: 'com.harshit.lifeos.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehaqWATpMdSJLXuUjFOY4dTLKRepu1gQ',
    appId: '1:52071196214:ios:a19255584a64ca14b85a97',
    messagingSenderId: '52071196214',
    projectId: 'lifeos-63a2c',
    storageBucket: 'lifeos-63a2c.firebasestorage.app',
    iosClientId: '52071196214-rv7b382mk3sreukgm83d8aesete7f4sn.apps.googleusercontent.com',
    iosBundleId: 'com.harshit.lifeos.lifeos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3EnxmAMeCkDGkk-CdFg53IThglpKOXdg',
    appId: '1:52071196214:web:649d0aedf07c3cc6b85a97',
    messagingSenderId: '52071196214',
    projectId: 'lifeos-63a2c',
    authDomain: 'lifeos-63a2c.firebaseapp.com',
    storageBucket: 'lifeos-63a2c.firebasestorage.app',
    measurementId: 'G-FK6KXNJ83P',
  );
}
